---
# Camp6
# MGMT: 10.31.205.6/32
# DHCP: 10.31.204.128/25
# MESH: 10.31.205.21/32

ipv6_prefix: 2001:bf7:750:5800::/56

networks:
  - vid: 20
    role: mesh
    name: mesh_camp
    prefix: 10.31.205.22/32
    ipv6_subprefix: -12
    mesh_ap: camp6
    mesh_radio: 11g_standard
    mesh_iface: mesh
    mesh_metric: 1024

  - vid: 40
    role: dhcp
    name: dhcp
    prefix: 10.31.204.128/25
    ipv6_subprefix: -13
    inbound_filtering: true
    enforce_client_isolation: true
    untagged: true
    assignments:
      camp6: 1

  - vid: 42
    role: mgmt
    prefix: 10.31.205.6/32
    gateway: 1
    dns: 1
    ipv6_subprefix: 6
    assignments:
      camp6: 1

location__channel_assignments_11a_standard__to_merge:
  camp2: 40-20

location__channel_assignments_11g_standard__to_merge:
  camp2: 13-20
